[package]
name                = "rsmus"
version             = "0.0.1-alpha"
authors             = ["evieluvsrainbows"]
edition             = "2024"

[dependencies]
audiotags           = "0.5.0"
clap                = { version = "4.6.6", features = ["derive"] }
claxon              = "0.4.3"
cursive             = { version = "0.21.0", default-features = false, features = ["crossterm-backend"] }
rayon               = "1.12.0"
rodio               = "0.22.2"
